ALTER TABLE task ADD COLUMN IF NOT EXISTS detail TEXT;
ALTER TABLE task ADD COLUMN IF NOT EXISTS start_not_before VARCHAR(255);
ALTER TABLE task ADD COLUMN IF NOT EXISTS end_not_after VARCHAR(255);
ALTER TABLE task ADD COLUMN IF NOT EXISTS estimated_duration VARCHAR(255);
